defmodule Catapult.Repo.Migrations.AddEventStore do
  use Ecto.Migration

  # Infrastructure persistence (conventions §6): EventStore owns its
  # tables under its reserved prefix — a dedicated Postgres schema
  # (conventions §6's `eventstore.*` — the schema-qualified form, since
  # the library's own namespacing knob is a schema rather than a table
  # prefix); app code reaches them only through the EventStore/Commanded
  # APIs (systems/engine.md). The engine is what needs this, but the
  # path is foundation's mapped file (`systems/foundation.md`'s own
  # Initial-vs-target note: "Target: EventStore migrations (with
  # engine)"), same split `systems/engine.md` records for this ticket.
  #
  # The schema statements are generated by the pinned `eventstore` dep
  # itself (`EventStore.Sql.Init.statements/1`) rather than hand-copied:
  # that is the library's own DDL, kept in lockstep with the adapter we
  # actually run, and it is what `mix event_store.init` runs internally
  # against a Postgrex connection outside of Ecto. Wrapping it in an
  # Ecto migration is what lets one migration runner
  # (`mix ecto.migrate --migrations-path priv/repo/migrations_infra`)
  # own both Oban's and the event store's schema, matching "One Repo"
  # (conventions §6) at the level that matters — one migration path —
  # without forcing the event store's own connection through
  # `Catapult.Repo`'s pool.
  @schema "eventstore"

  def up do
    execute(~s(CREATE SCHEMA "#{@schema}"))

    config = [schema: @schema, column_data_type: "jsonb"]

    for statement <- EventStore.Sql.Init.statements(config) do
      execute(statement)
    end

    # The first statement above is `SET LOCAL search_path TO
    # "eventstore"`, which lives for the rest of this migration's
    # transaction — Ecto records its own version row in that same
    # transaction, so leaving the path pointed at the new schema makes
    # that insert resolve `schema_migrations` to the event store's own
    # table of that name (different columns entirely) instead of
    # Ecto's. Restored before the transaction ends rather than scoped
    # more narrowly, because `SET LOCAL` has no narrower scope than
    # "the rest of this transaction" to give it.
    execute(~s(SET LOCAL search_path TO "public";))
  end

  def down do
    execute(~s(DROP SCHEMA "#{@schema}" CASCADE))
  end
end
