defmodule Catapult.Engine.Commands.CommitDraft do
  @moduledoc """
  Commits a draft body for a node (dsl-syntax.md §3).

  Every value is supplied by the caller — `draft_id`, `committed_at`,
  every minted child's `node_id` — none generated by the aggregate or
  reducer (the purity floor, `systems/engine.md`). Producing these
  values (a fresh id, `DateTime.utc_now/0`) is the command edge's job:
  whatever dispatches this command, not the aggregate that validates
  it or the reducer that folds its event.
  """

  @enforce_keys [:project_id, :node_id, :tier, :scope_key, :draft_id, :body_sha, :committed_at]
  defstruct [
    :project_id,
    :node_id,
    :tier,
    :scope_key,
    :parent_node_id,
    :draft_id,
    :body_sha,
    :committed_at,
    :actor_id,
    fields: %{},
    mints: [],
    edges: [],
    produces: []
  ]
end
